if(API_DEFINED)
  return()
endif()
set(API_DEFINED TRUE)

include(GNUInstallDirs)

set(MY_PROJECT_APP_PATH "${CMAKE_INSTALL_BINDIR}")
set(MY_PROJECT_LIBEXEC_PATH "${CMAKE_INSTALL_LIBEXECDIR}/${MY_PROJECT_ID}")
set(MY_PROJECT_LIBRARY_BASE_PATH "${CMAKE_INSTALL_LIBDIR}")
set(MY_PROJECT_LIBRARY_PATH  "${MY_PROJECT_LIBRARY_BASE_PATH}/${MY_PROJECT_ID}")
set(MY_PROJECT_LIBRARY_ARCHIVE_PATH "${MY_PROJECT_LIBRARY_PATH}")
set(MY_PROJECT_HEADER_INSTALL_PATH "include/${MY_PROJECT_ID}")
set(MY_PROJECT_DATA_PATH "${CMAKE_INSTALL_DATAROOTDIR}")
set(MY_PROJECT_DOC_PATH "${CMAKE_INSTALL_DATAROOTDIR}/doc")


if (WIN32)
  set(MY_PROJECT_RPATH_BASE "")
  set(MY_PROJECT_LIB_RPATH "")
else()
  set(MY_PROJECT_RPATH_BASE "\$ORIGIN")
  set(MY_PROJECT_LIB_RPATH "\$ORIGIN")
endif ()

include(${CMAKE_CURRENT_LIST_DIR}/ProjectAPIInternal.cmake)